%% Generate 3D map
function map = generate_map3D(K, Nx, Ny, Nz)
    % Set Tx parameters
    Pt = 2000; % Transmit power = 2W
    freq = 1e9; % Frequency = 1 GHz

    N = Nx * Ny * Nz;
    map = struct( ...
        'sparsity',   K, ...
        'width',      Nx, ...
        'height',     Ny, ...
        'depth',      Nz, ...
        'size',       N, ...
        'Tx',         [], ...
        'omega_real', [] ...
    );

    Tx(K) = struct( ...
        'power',   [], ...
        'freq',    [], ...
        'id',      [], ...
        'x',       [], ...
        'y',       [], ...
        'z',       [], ...
        'pos',     [], ...
        'gain',    [], ...
        'gain_ln', [] ...
    );




    map.Tx = Tx;
    omega_real = sparse([Tx.pos], ones(1,K), [Tx.power], N, 1);
    map.omega_real = omega_real;
end


function ln = db_to_ln(db)
    ln = 10.^(db./10);
end

function db = ln_to_db(ln)
    db = 10.*log10(ln);
end
